c_compiler:
  - gcc
c_compiler_version:
  - "12"
c_stdlib:
  - sysroot
c_stdlib_version:
  - "2.17"
cxx_compiler:
  - gxx
cxx_compiler_version:
  - "12"
cuda:
  - 12.6.*
cuda_compiler_version:
  - "12.6"
